#!/bin/sh
# CapMesh — tailnet install (POSIX sh).
# Served public (no bearer) at https://capmesh.asg.ts.net/install.sh
# Usage:  curl -fsSL https://capmesh.asg.ts.net/install.sh | sh
# Tailnet-only: reachable only over the asg Tailscale tailnet.
set -eu

BASE_URL="${CAPMESH_BASE_URL:-https://capmesh.asg.ts.net}"
CONFIG_DIR="${HOME}/.config/capmesh-harness"
ENV_FILE="$CONFIG_DIR/capmesh.env"

say()  { printf '[capmesh-install] %s\n' "$*"; }
die()  { printf '[capmesh-install] ERROR: %s\n' "$*" >&2; exit 1; }
note() { printf '[capmesh-install] note: %s\n' "$*"; }

# === Phase 1: Verify tailnet + connectivity ===

say "verifying tailnet membership..."
command -v tailscale >/dev/null 2>&1 || \
  die "tailscale not found. Install it and join the asg tailnet first."

tailscale status >/dev/null 2>&1 || \
  die "not connected to the tailnet. Run: tailscale up"

say "checking reachability to $BASE_URL..."
if ! curl -fsS --max-time 5 "$BASE_URL/api/v1/whoami" >/dev/null 2>&1; then
  note "initial reachability check did not respond; proceeding anyway (provisioning is lazy)."
fi

# === Phase 2: Install capmesh CLI ===

PREFIX="${CAPMESH_PREFIX:-$HOME/.local/bin}"
mkdir -p "$PREFIX"

CLIENT="$PREFIX/capmesh"
say "installing capmesh CLI to $CLIENT..."

cat > "$CLIENT" <<'EOFCLI'
#!/bin/sh
set -eu
CAPMESH_BASE_URL="${CAPMESH_BASE_URL:-https://capmesh.asg.ts.net}"
_auth() {
  [ -n "${CAPMESH_BEARER_TOKEN:-}" ] && printf 'Authorization: Bearer %s\n' "$CAPMESH_BEARER_TOKEN"
}
_curl_auth() {
  if [ -n "${CAPMESH_BEARER_TOKEN:-}" ]; then
    curl -fsS -H "$(_auth)" "$@"
  else
    curl -fsS "$@"
  fi
}
case "${1:-help}" in
  whoami)
    shift
    _curl_auth "$CAPMESH_BASE_URL/api/v1/whoami"
    ;;
  search)
    shift
    _curl_auth --get --data-urlencode "q=$*" "$CAPMESH_BASE_URL/cap/search"
    ;;
  load)
    shift
    _curl_auth --get --data-urlencode "uri=$*" "$CAPMESH_BASE_URL/api/v1/load"
    ;;
  bootstrap)
    _curl_auth "$CAPMESH_BASE_URL/bootstrap"
    ;;
  help|*)
    printf 'capmesh - tailnet capability mesh client\n'
    printf 'Usage:\n'
    printf '  capmesh whoami              print identity\n'
    printf '  capmesh search <query>      search capabilities\n'
    printf '  capmesh load <uri>          fetch capability descriptor\n'
    printf '  capmesh bootstrap           initialize namespace\n'
    printf 'Base URL: %s (tailnet-only, identity = your tailnet login)\n' "$CAPMESH_BASE_URL"
    ;;
esac
EOFCLI

chmod 0755 "$CLIENT"
say "CLI installed: $CLIENT"

# === Phase 3: Write config + env file ===

say "creating config directory $CONFIG_DIR..."
mkdir -p "$CONFIG_DIR"

say "writing $ENV_FILE..."
cat > "$ENV_FILE" <<EOFENV
# CapMesh Configuration
# Auto-generated by install.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source this file or set CAPMESH_BASE_URL for CLI + MCP integration.

# Mesh endpoint (tailnet-only, identity injected by tailscale serve).
CAPMESH_BASE_URL="$BASE_URL"

# Optional: bearer token for legacy/external access (not needed for tailnet identity).
# CAPMESH_BEARER_TOKEN="<token>"

# Metadata for MCP server registration.
CAPMESH_CLIENT_INSTALL_PATH="$CLIENT"
CAPMESH_CONFIG_DIR="$CONFIG_DIR"
EOFENV

chmod 0600 "$ENV_FILE"
note "env file written (mode 0600): $ENV_FILE"
note "source this for CLI access:  source $ENV_FILE"

# === Phase 4: MCP Server registration ===

MCP_CONFIG="$CONFIG_DIR/capmesh-mcp.json"
say "registering capmesh as MCP server..."

cat > "$MCP_CONFIG" <<EOFMCP
{
  "name": "capmesh",
  "description": "CapMesh — tailnet capability discovery and schema loading",
  "command": "sh",
  "args": [
    "-c",
    "source '$ENV_FILE' && exec $CLIENT"
  ],
  "env": {
    "CAPMESH_BASE_URL": "$BASE_URL"
  }
}
EOFMCP

chmod 0644 "$MCP_CONFIG"
note "MCP server config: $MCP_CONFIG"
note "integrate into ~/.claude.json mcpServers: {\"capmesh\": $MCP_CONFIG}"

# === Phase 5: Prime namespace + doctor check ===

say "priming your namespace via /api/v1/whoami..."
WHOAMI_RESPONSE=$(curl -fsS --max-time 10 "$BASE_URL/api/v1/whoami" 2>/dev/null || echo "")

if [ -n "$WHOAMI_RESPONSE" ]; then
  say "namespace primed successfully (identity auto-provisioned)."
  note "response: (not echoed; identity + capabilities loaded server-side)"
else
  note "whoami endpoint not yet available; your namespace will provision on first capmesh CLI call."
fi

say "running capmesh auth doctor..."
if [ -x "$CLIENT" ]; then
  if $CLIENT whoami >/dev/null 2>&1; then
    say "✓ auth doctor: passed. capmesh is ready."
  else
    note "auth doctor: /whoami returned non-zero; check tailnet + $BASE_URL reachability."
  fi
else
  note "capmesh CLI not executable; skipping doctor."
fi

# === Phase 6: Summary ===

say ""
say "installation complete."
say "next steps:"
say "  1. source $ENV_FILE"
say "  2. capmesh whoami"
say "  3. capmesh search <topic>"
say ""
say "tailnet-only access via $BASE_URL"
say "identity = your Tailscale login (no bearer required over tailnet)"
