# CapMesh — tailnet install (PowerShell).
# Served public (no bearer) at https://capmesh.asg.ts.net/install.ps1
# Usage:  irm https://capmesh.asg.ts.net/install.ps1 | iex
# Tailnet-only: reachable only over the asg Tailscale tailnet.

$ErrorActionPreference = 'Stop'

# === Configuration ===

$BaseUrl = if ($env:CAPMESH_BASE_URL) { $env:CAPMESH_BASE_URL } else { 'https://capmesh.asg.ts.net' }
$ConfigDir = Join-Path $HOME '.config' 'capmesh-harness'
$EnvFile = Join-Path $ConfigDir 'capmesh.env'
$Timestamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

# === Logging ===

function Say {
  param([string]$Message)
  Write-Host "[capmesh-install] $Message"
}

function Die {
  param([string]$Message)
  Write-Error "[capmesh-install] ERROR: $Message"
  exit 1
}

function Note {
  param([string]$Message)
  Write-Host "[capmesh-install] note: $Message" -ForegroundColor Yellow
}

# === Phase 1: Verify tailnet + connectivity ===

Say 'verifying tailnet membership...'
$ts = Get-Command tailscale -ErrorAction SilentlyContinue
if (-not $ts) {
  Die 'tailscale not found. Install it and join the asg tailnet first.'
}

try {
  & tailscale status | Out-Null
} catch {
  Die 'not connected to the tailnet. Run: tailscale up'
}

Say "checking reachability to $BaseUrl..."
try {
  Invoke-RestMethod -Uri "$BaseUrl/api/v1/whoami" -TimeoutSec 5 -ErrorAction SilentlyContinue | Out-Null
} catch {
  Note 'initial reachability check did not respond; proceeding anyway (provisioning is lazy).'
}

# === Phase 2: Install capmesh CLI ===

$Prefix = if ($env:CAPMESH_PREFIX) { $env:CAPMESH_PREFIX } else { Join-Path $HOME '.local' 'bin' }
if (-not (Test-Path $Prefix)) {
  New-Item -ItemType Directory -Force -Path $Prefix | Out-Null
}

$ClientPath = Join-Path $Prefix 'capmesh.ps1'
Say "installing capmesh CLI to $ClientPath..."

$ClientScript = @'
# CapMesh — PowerShell client
# Identity = Tailscale login (no bearer required over tailnet)

$ErrorActionPreference = 'Stop'

$BaseUrl = if ($env:CAPMESH_BASE_URL) { $env:CAPMESH_BASE_URL } else { 'https://capmesh.asg.ts.net' }

function Invoke-CapMesh {
  param(
    [string]$Method = 'GET',
    [string]$Endpoint,
    [hashtable]$Params
  )
  $Headers = @{}
  if ($env:CAPMESH_BEARER_TOKEN) {
    $Headers['Authorization'] = "Bearer $($env:CAPMESH_BEARER_TOKEN)"
  }

  $Uri = if ($Params.Count -gt 0) {
    $QueryString = @($Params.GetEnumerator() | ForEach-Object { "$($_.Key)=$([uri]::EscapeDataString($_.Value))" }) -join '&'
    "$BaseUrl$Endpoint`?$QueryString"
  } else {
    "$BaseUrl$Endpoint"
  }

  Invoke-RestMethod -Method $Method -Uri $Uri -Headers $Headers
}

switch ($args[0]) {
  'whoami' {
    Invoke-CapMesh -Endpoint '/api/v1/whoami'
  }
  'search' {
    $query = $args[1..($args.Length - 1)] -join ' '
    Invoke-CapMesh -Endpoint '/cap/search' -Params @{ q = $query }
  }
  'load' {
    $uri = $args[1..($args.Length - 1)] -join ' '
    Invoke-CapMesh -Endpoint '/api/v1/load' -Params @{ uri = $uri }
  }
  'bootstrap' {
    Invoke-CapMesh -Endpoint '/bootstrap'
  }
  'help' {
    Write-Host 'capmesh - tailnet capability mesh client'
    Write-Host 'Usage:'
    Write-Host '  capmesh whoami              print identity'
    Write-Host '  capmesh search <query>      search capabilities'
    Write-Host '  capmesh load <uri>          fetch capability descriptor'
    Write-Host '  capmesh bootstrap           initialize namespace'
    Write-Host "Base URL: $BaseUrl (tailnet-only, identity = your tailnet login)"
  }
  default {
    Write-Host 'capmesh - tailnet capability mesh client'
    Write-Host 'Usage:'
    Write-Host '  capmesh whoami              print identity'
    Write-Host '  capmesh search <query>      search capabilities'
    Write-Host '  capmesh load <uri>          fetch capability descriptor'
    Write-Host '  capmesh bootstrap           initialize namespace'
    Write-Host "Base URL: $BaseUrl (tailnet-only, identity = your tailnet login)"
  }
}
'@

Set-Content -Path $ClientPath -Value $ClientScript -Encoding UTF8
Say "CLI installed: $ClientPath"

# === Phase 3: Write config + env file ===

Say "creating config directory $ConfigDir..."
if (-not (Test-Path $ConfigDir)) {
  New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
}

Say "writing $EnvFile..."

$EnvFileContent = @"
# CapMesh Configuration
# Auto-generated by install.ps1 at $Timestamp
# Source this file or set CAPMESH_BASE_URL for CLI + MCP integration.

# Mesh endpoint (tailnet-only, identity injected by tailscale serve).
CAPMESH_BASE_URL=$BaseUrl

# Optional: bearer token for legacy/external access (not needed for tailnet identity).
# CAPMESH_BEARER_TOKEN=<token>

# Metadata for MCP server registration.
CAPMESH_CLIENT_INSTALL_PATH=$ClientPath
CAPMESH_CONFIG_DIR=$ConfigDir
"@

Set-Content -Path $EnvFile -Value $EnvFileContent -Encoding UTF8
(Get-Item $EnvFile).Attributes = 'Normal'  # Clear any inherited attributes
Note "env file written: $EnvFile"
Note "source this for CLI access:  . `"$EnvFile`""

# === Phase 4: MCP Server registration ===

$MCP_CONFIG = Join-Path $ConfigDir 'capmesh-mcp.json'
Say 'registering capmesh as MCP server...'

$MCP_ConfigContent = @{
  name = 'capmesh'
  description = 'CapMesh — tailnet capability discovery and schema loading'
  command = 'pwsh'
  args = @(
    '-NoProfile',
    '-Command',
    ". `"$EnvFile`"; & `"$ClientPath`""
  )
  env = @{
    CAPMESH_BASE_URL = $BaseUrl
  }
} | ConvertTo-Json -Depth 10

Set-Content -Path $MCP_CONFIG -Value $MCP_ConfigContent -Encoding UTF8
Note "MCP server config: $MCP_CONFIG"
Note "integrate into `$PROFILE or ~/.claude.json mcpServers: {`"capmesh`": `"$MCP_CONFIG`"}"

# === Phase 5: Prime namespace + doctor check ===

Say 'priming your namespace via /api/v1/whoami...'
try {
  $WhoamiResponse = Invoke-RestMethod -Uri "$BaseUrl/api/v1/whoami" -TimeoutSec 10 -ErrorAction SilentlyContinue
  if ($WhoamiResponse) {
    Say 'namespace primed successfully (identity auto-provisioned).'
    Note 'response: (not echoed; identity + capabilities loaded server-side)'
  }
} catch {
  Note 'whoami endpoint not yet available; your namespace will provision on first capmesh CLI call.'
}

Say 'running capmesh auth doctor...'
try {
  & pwsh -NoProfile -Command ". `"$EnvFile`"; & `"$ClientPath`" whoami" -ErrorAction SilentlyContinue | Out-Null
  Say '✓ auth doctor: passed. capmesh is ready.'
} catch {
  Note 'auth doctor: /whoami returned non-zero; check tailnet + reachability to $BaseUrl.'
}

# === Phase 6: Summary ===

Say ''
Say 'installation complete.'
Say 'next steps:'
Say "  1. . `"$EnvFile`""
Say '  2. capmesh whoami'
Say '  3. capmesh search <topic>'
Say ''
Say "tailnet-only access via $BaseUrl"
Say 'identity = your Tailscale login (no bearer required over tailnet)'
